<%@ page contentType="text/html; charset=UTF-8"%>
<link href="${ctx}/common/dhtmlxtree/css/dhtmlXTree.css" rel="stylesheet" type="text/css"></link>
<script type="text/javascript" src="${ctx}/common/dhtmlxtree/js/dhtmlXCommon.js"></script>
<script type="text/javascript" src="${ctx}/common/dhtmlxtree/js/dhtmlXTree.js"></script>

<script type="text/javascript">
var dhtmlXTreeImPath="${ctx}/common/dhtmlxtree/imgs/";
</script>