<script src="${ctx}/common/codemirror/codemirror.js" type="text/javascript"></script>
<script src="${ctx}/common/codemirror/mode/xml/xml.js"></script>
<script src="${ctx}/common/codemirror/mode/javascript/javascript.js"></script>
<script src="${ctx}/common/codemirror/mode/css/css.js"></script>
<script src="${ctx}/common/codemirror/mode/htmlmixed/htmlmixed.js"></script>
<script src="${ctx}/common/codemirror/addon/hint/show-hint.js"></script>
<script src="${ctx}/common/codemirror/addon/hint/xml-hint.js"></script>
<script src="${ctx}/common/codemirror/addon/hint/html-hint.js"></script>
<script src="${ctx}/common/codemirror/addon/hint/css-hint.js"></script>
<script src="${ctx}/common/codemirror/addon/hint/javascript-hint.js"></script>
<script src="${ctx}/common/codemirror/addon/search/search.js"></script>
<script src="${ctx}/common/codemirror/addon/search/searchcursor.js"></script>
<script src="${ctx}/common/codemirror/addon/dialog/dialog.js"></script>
<script src="${ctx}/common/codemirror/addon/fold/foldcode.js"></script>
<script src="${ctx}/common/codemirror/addon/fold/foldgutter.js"></script>
<script src="${ctx}/common/codemirror/addon/fold/brace-fold.js"></script>
<script src="${ctx}/common/codemirror/addon/fold/xml-fold.js"></script>
<script src="${ctx}/common/codemirror/addon/fold/comment-fold.js"></script>
<script src="${ctx}/common/codemirror/addon/display/fullscreen.js"></script>
<script src="${ctx}/common/codemirror/addon/selection/active-line.js"></script>

<link href="${ctx}/common/codemirror/codemirror.css" rel="stylesheet" />
<link href="${ctx}/common/codemirror/addon/hint/show-hint.css" rel="stylesheet" />
<link href="${ctx}/common/codemirror/addon/fold/foldgutter.css" rel="stylesheet" />
<link href="${ctx}/common/codemirror/addon/dialog/dialog.css" rel="stylesheet" />
<link href="${ctx}/common/codemirror/addon/display/fullscreen.css" rel="stylesheet" />
<link href="${ctx}/common/codemirror/theme/eclipse.css" rel="stylesheet" />