<%@ page contentType="text/html; charset=UTF-8"%>
<link href="${ctx}/common/menu/tree_right_menu.css" rel="stylesheet" type="text/css">	
<link href="${ctx}/common/xloadtree/xtree.css" rel="stylesheet" type="text/css">	
<script type="text/javascript" src="${ctx}/common/xloadtree/cxtree.js"></script>
<script type="text/javascript" src="${ctx}/common/xloadtree/xmlextras.js"></script>
<script type="text/javascript" src="${ctx}/common/menu/tree_right_menu.js"></script>
<script type="text/javascript">

/// XP Look
webFXTreeConfig.rootIcon	= "${ctx}/common/xloadtree/images/xp/folder.png";
webFXTreeConfig.openRootIcon	= "${ctx}/common/xloadtree/images/xp/openfolder.png";
webFXTreeConfig.folderIcon	= "${ctx}/common/xloadtree/images/xp/folder.png";
webFXTreeConfig.openFolderIcon	= "${ctx}/common/xloadtree/images/xp/openfolder.png";
webFXTreeConfig.fileIcon	= "${ctx}/common/xloadtree/images/xp/file.png";
webFXTreeConfig.lMinusIcon	= "${ctx}/common/xloadtree/images/xp/Lminus.png";
webFXTreeConfig.lPlusIcon	= "${ctx}/common/xloadtree/images/xp/Lplus.png";
webFXTreeConfig.tMinusIcon	= "${ctx}/common/xloadtree/images/xp/Tminus.png";
webFXTreeConfig.tPlusIcon	= "${ctx}/common/xloadtree/images/xp/Tplus.png";
webFXTreeConfig.iIcon		= "${ctx}/common/xloadtree/images/xp/I.png";
webFXTreeConfig.lIcon		= "${ctx}/common/xloadtree/images/xp/L.png";
webFXTreeConfig.tIcon		= "${ctx}/common/xloadtree/images/xp/T.png";
webFXTreeConfig.blankIcon	= "${ctx}/common/xloadtree/images/blank.png";
</script>