<link href="${ctx}/common/MultiUpload/css/default.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="${ctx}/common/MultiUpload/swfupload/swfupload.js"></script>
<script type="text/javascript" src="${ctx}/common/MultiUpload/js/handlers.js"></script>
<script type="text/javascript" src="${ctx}/common/MultiUpload/js/fileprogress.js"></script>
<script type="text/javascript" src="${ctx}/common/MultiUpload/js/swfupload.queue.js"></script>