<%@ page contentType="text/html; charset=UTF-8"%>
<link href='<c:url value="/common/menu/tree_right_menu.css"/>' rel="stylesheet" type="text/css">	
<link href='<c:url value="/common/xloadtree/xtree.css"/>' rel="stylesheet" type="text/css">	
<script type="text/javascript" src="<%=request.getContextPath()%>/common/xloadtree/xtree.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/common/xloadtree/xmlextras.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/common/xloadtree/xloadtree.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/common/menu/tree_right_menu.js"></script>
<script type="text/javascript">

/// XP Look
webFXTreeConfig.rootIcon	= '<c:url value="/common/xloadtree/images/xp/folder.png"/>';
webFXTreeConfig.openRootIcon	= '<c:url value="/common/xloadtree/images/xp/openfolder.png"/>';
webFXTreeConfig.folderIcon	= '<c:url value="/common/xloadtree/images/xp/folder.png"/>';
webFXTreeConfig.openFolderIcon	= '<c:url value="/common/xloadtree/images/xp/openfolder.png"/>';
webFXTreeConfig.fileIcon	= '<c:url value="/common/xloadtree/images/xp/file.png"/>';
webFXTreeConfig.lMinusIcon	= '<c:url value="/common/xloadtree/images/xp/Lminus.png"/>';
webFXTreeConfig.lPlusIcon	= '<c:url value="/common/xloadtree/images/xp/Lplus.png"/>';
webFXTreeConfig.tMinusIcon	= '<c:url value="/common/xloadtree/images/xp/Tminus.png"/>';
webFXTreeConfig.tPlusIcon	= '<c:url value="/common/xloadtree/images/xp/Tplus.png"/>';
webFXTreeConfig.iIcon		= '<c:url value="/common/xloadtree/images/xp/I.png"/>';
webFXTreeConfig.lIcon		= '<c:url value="/common/xloadtree/images/xp/L.png"/>';
webFXTreeConfig.tIcon		= '<c:url value="/common/xloadtree/images/xp/T.png"/>';
webFXTreeConfig.blankIcon	= '<c:url value="/common/xloadtree/images/blank.png"/>';
</script>