package com.cyberway.common.domain;

import java.util.HashSet;
import java.util.Set;


/**
 * CorePortal generated by MyEclipse - Hibernate Tools
 */

public class CorePortal  implements java.io.Serializable {


    // Fields    
	private Long oid;
	
     private String code;
     private String name;
     private String remark;
     /** nullable persistent field */
     private String inco;
     
     /** nullable persistent field */
     private String openInco;
     
     /** nullable persistent field */
     private String closeInco;     


    // Constructors

    /** default constructor */
    public CorePortal() {
    }
	/** minimal constructor */
    public CorePortal(Long oid) {
        this.oid = oid;
    }
	public String getCloseInco() {
		return closeInco;
	}
	public void setCloseInco(String closeInco) {
		this.closeInco = closeInco;
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getInco() {
		return inco;
	}
	public void setInco(String inco) {
		this.inco = inco;
	}
	public Long getOid() {
		return oid;
	}
	public void setOid(Long oid) {
		this.oid = oid;
	}
	public String getOpenInco() {
		return openInco;
	}
	public void setOpenInco(String openInco) {
		this.openInco = openInco;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}

}